### DISCUSSION TITLE
Accessing fields by name

### DISCUSSION THREAD

**Discussion by jslezosky** [biojppm/rapidyaml#231] [Q&A] [answered]
Using the following yaml in file "test.yaml":

```yaml
commands:
    IAU_BOOT_RST:
        - dmoab_scid: {value: 1, type: uint8_t, size: 4}
        - dmoab_opcode: {value: 2, type: uint8_t, size: 4}
        - dmoab_extension: {value: 3, type: uint8_t, size: 8}
        - dmoab_operand: {value: [0,0,0,0,17], type: vector<uint8_t>, size: 40}
        - dmoab_crc: {value: 0, type: uint8_t, size: 8}
    IAU_WD_EN:
        - dmoab_scid: {value: 4, type: uint8_t, size: 4}
        - dmoab_opcode: {value: 5, type: uint8_t, size: 4}
        - dmoab_extension: {value: 6, type: uint8_t, size: 8}
        - dmoab_operand: {value: [0,0,0,0,34], type: vector<uint8_t>, size: 40}
        - dmoab_crc: {value: 0, type: uint8_t, size: 8}
```
		
I want to access the integer value of dmoab_extension, size for each command.
I thought I could access the fields by name using the following code:

```c++
std::string contents = file_get_contents<std::string>("test.yaml");
ryml::Tree tree = ryml::parse_in_arena(ryml::to_csubstr(contents)); 

ryml::NodeRef root = tree["commands"];

// iterate children
for (ryml::NodeRef const& command : root.children())
{
    std::cout << "size " << command["IAU_BOOT_RST"]["dmoab_extension"]["size"].val() << std::endl
}
```
		
Of course this code crashes.
What is the correct method for accessing children by name?
Once I do access "size", how do I read it as an integer or uint8_t?

**Comment by biojppm** [comment, marked as answer]
Your loop variable is already the command, so you are looking twice for `IAU_BOOT_RST`. That is, you are doing the equivalent to `tree["commands"]["IAU_BOOT_RST"]["IAU_BOOT_RST"]["dmoab_extension"]["size"]`, and it fails.

What you want is simply this:
```c++
for (ryml::NodeRef const& cmd : tree["commands"].children())
  std::cout << cmd.key() << ": size=" << cmd["dmoab_extension"]["size"].val() << "\n";
```

As for the conversion, [it's in the quickstart](https://github.com/biojppm/rapidyaml/blob/213b201d264139cd1b887790197e08850af628e3/samples/quickstart.cpp#L335). In this case:
```c++
int size;
cmd["dmoab_extension"]["size"] >> size;
```

**Reply by jslezosky** [reply]
I really appreciate you working with me on this.
I know this should work, but it crashes.
On the command line I get:

C:\EASY\rapidyaml\src_singleheader\ryml_all.hpp:24170:check failed: (is_map(node))

From the debugger, it is crashing at:
size_t Tree::find_child(size_t node, csubstr const& name) const
{
    _RYML_CB_ASSERT(m_callbacks, node != NONE);
    **_RYML_CB_ASSERT(m_callbacks, is_map(node));**

With node = 2, name = "dmoab_extension"

I must have something fundamentally wrong, but I can't figure it out.

**Reply by jslezosky** [reply]
I tried the following code:
```c++
for (ryml::NodeRef const& cmd : tree["commands"].children())
{
    std::cout << cmd.key() << ": size=" << cmd[0]["dmoab_scid"]["size"].val() << "\n";
    std::cout << cmd.key() << ": size=" << cmd[0]["dmoab_extension"]["size"].val() << "\n";
}
```
the `dmoab_scid` line prints : `IAU_BOOT_RST: size=4`
but the `dmoab_extension` line crashes.

**Reply by biojppm** [reply]
I overlooked that each command is a sequence and not a map. So to get at the `scid/extension` nodes you'll have to provide the proper sequence index:
```c++
for (ryml::NodeRef const& cmd : tree["commands"].children())
{
    // _scid is at position 0
    std::cout << cmd.key() << ": size=" << cmd[0]["dmoab_scid"]["size"].val() << "\n";
    // NOTE _extension is at position 2
    std::cout << cmd.key() << ": size=" << cmd[2]["dmoab_extension"]["size"].val() << "\n";
}
```
The solution is in realizing that `dmoab_extension` is the single child of `cmd[2]` and not `cmd[0]`.

The assert is firing because when you write `cmd[0]["dmoab_extension"]`, the `cmd[0]` part is going to return the first child node of `cmd` which is a map with a single keyval `dmoab_scid: {..., size: 4}`. Then `cmd[0]["dmoab_extension"]` does not exist, so it returns a seed node (ie, is typeless and can be written but not read), so calling `cmd[0]["dmoab_extension"]["size"]` fails because `cmd[0]["dmoab_extension"]` is typeless and not a map.

BTW, why use a sequence structure for the command? Why not a map directly, like this?
```yaml
commands:
  IAU_BOOT_RST:
    # notice it is not this:
    #- dmoab_scid: {value: 1, type: uint8_t, size: 4}
    dmoab_scid: {value: 1, type: uint8_t, size: 4}
    dmoab_opcode: {value: 2, type: uint8_t, size: 4}
    dmoab_extension: {value: 3, type: uint8_t, size: 8}
    dmoab_operand: {value: [0,0,0,0,17], type: vector<uint8_t>, size: 40}
    dmoab_crc: {value: 0, type: uint8_t, size: 8}
  IAU_WD_EN:
    dmoab_scid: {value: 4, type: uint8_t, size: 4}
    dmoab_opcode: {value: 5, type: uint8_t, size: 4}
    dmoab_extension: {value: 6, type: uint8_t, size: 8}
    dmoab_operand: {value: [0,0,0,0,34], type: vector<uint8_t>, size: 40}
    dmoab_crc: {value: 0, type: uint8_t, size: 8}
```
With the above structure you would not need `cmd[0]["dmoab_scid"]` and `cmd[2]["dmoab_extension"]`, just `cmd["dmoab_scid"]` and `cmd["dmoab_extension"]`, as would generally be expected.
