### DISCUSSION TITLE
parse_in_place preserves structure but no keys/value extracted

### DISCUSSION THREAD

**Discussion by shivamkedia17** [biojppm/rapidyaml#474] [Q&A]
Hi,
Trying to perform some input (schema) validation using this library. I noticed that on some occasions, the `tree` obtained after parsing has the structure of the file, but _doesn't have keys/values._ I'm slightly new to cpp, and it's been a couple hours but I haven't been able to figure out whether it's some memory issue or if I'm using some functions incorrectly.

Snippet of the `yaml` buffer:
![Screenshot 2024-10-12 at 00 40 42](https://github.com/user-attachments/assets/7330abfa-58d3-4ec1-ba1d-f9f0c139662b)

After parsing, the buffer and creating a tree:
```cpp
    tree = ryml::parse_in_place( filepath.filename().string().c_str(), load_file(filepath).data() );
```

Snippet of `std::cout << tree << std::endl;`
![Screenshot 2024-10-12 at 00 41 49](https://github.com/user-attachments/assets/85c68d6e-1bd1-4ca6-a127-1ade60b2d253)

This is the yaml file for reference:
```yml
Views:
- Angles: 0 0 0
  Vertices:
  - A -4 1
  - B -4 -1
  - C 4 -1
  - D 4 1
  - E 4 1
  - F 4 -1
  - G -4 1
  - H -4 -1
- Angles: 0 -90 0
  Vertices:
  - A 2 1
  - B 2 -1
  - C 2 -1
  - D 2 1
  - E -2 1
  - F -2 -1
  - G -2 1
  - H -2 -1
- Angles: 90 0 0
  Vertices:
  - A -4 -2
  - B -4 -2
  - C 4 -2
  - D 4 -2
  - E 4 2
  - F 4 2
  - G -4 2
  - H -4 2

Edges:
- E1: A B
- E2: B C
- E3: C D
- E4: D A
- E5: D E
- E6: E F
- E7: F C
- E8: B H
- E9: H G
- E10: G A
- E11: G E
- E12: F H

Loops:
- loop1:
  - + E1
  - + E2
  - + E3
  - + E4
- loop2:
  - + E5
  - + E6
  - + E7
  - + E8
- loop3:
  - + E9
  - + E10
  - + E11
  - + E12

```

This is the rest of the code for reference:

```cpp

std::vector<char> InputValidator::load_file(const fs::path& file_path) {
    if (!fs::exists(file_path)) {
        throw std::runtime_error("Error: File does not exist.");
    }

    // Open the file in binary mode and position the cursor at the end
    std::ifstream file(file_path, std::ios::binary | std::ios::ate);
    if (!file) {
        throw std::runtime_error("Error: Could not open file.");
    }

    const std::streamsize file_size = file.tellg();
    std::vector<char> buffer(file_size);
    file.seekg(0, std::ios::beg);
    
    if (!file.read(buffer.data(), file_size)) {
        throw std::runtime_error("Error: Could not read file.");
    }

    std::cout << buffer.data() << std::endl;
    return buffer;
}

// Parses the YAML content into a ryml tree
void InputValidator::parse() {
    tree = ryml::parse_in_place( filepath.filename().string().c_str(), load_file(filepath).data() );
    std::cout << tree << std::endl;
}

// Validates Rules by calling sub-functions
void InputValidator::validate() const {
    validate_views();
}

// Validates "Views"
void InputValidator::validate_views() const {
    if (!tree["Views"].is_seq() || tree["Views"].num_children() != 3) {
        throw std::runtime_error("Error: There must be exactly 3 views.");
    }

    for (const auto view : tree["Views"].children())
    {
        std::cout << view << std::endl;
        validate_angles(view);
        validate_vertices(view);
    }

    std::cout << "Views validated" << std::endl;
}

// Validate: Each view has exactly 3 angles
void InputValidator::validate_angles(const ryml::ConstNodeRef view)
{
    std::cout << view << std::endl;
    std::cout << view.has_child("Angles") << "\n";
    std::cout << view.num_children() << "\n" << std::endl;

    if (!view.has_child("Angles") || view.num_children() != 3) {
        throw std::runtime_error("Error: Each view must have exactly 3 angles.");
    }
}
```

Any help is appreciated, thanks!
