### ISSUE TITLE
Difference between child and sibling in rapidyaml

### ISSUE THREAD

**Issue by ales-kunst** [biojppm/rapidyaml#127]
Hello, I am new to yaml and also to rapidyaml. I saw that the Tree structure among other things it has siblings and children elements. Now I presume that siblings are the Yaml elements which are on the same level as the element which is being queried with the Tree::next_sibling(node) and the children are the subelements of the queried element (I assume). Now my questions are the following:
- I have seen that siblings have next_sibling(node) function and children do not. Maybe I am missing here something. Can you tell me what? Maybe my understanding of siblings and children elements is wrong. Can you please explain me the difference?
- I have tried to iterate through all siblings in my Yaml content and on the last sibling element when I try to do the `yamlTree[lastSibling]` I get error: `ERROR: expected true: ch != NONE`. Below is the cpp code  and yaml file which fails (I have simplified the code for just accessing the last sibling). Now can you explain me what am I doing wrong here?

Cpp code which fails:
```
const std::string& yamlContents = <read contents from yaml file>;
const auto& contentsView = c4::to_csubstr(contents.c_str());
const auto& yamlTree = ryml::parse(contentsView);
size_t ls = yamlTree.last_sibling(1);
const auto& nr = yamlTree[ls];
```
Yaml file contents:

```
ca_cert: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
xmas: true
french-hens: 3
calling-birds:
   - huey
   - dewey
   - louie
   - fred
xmas-fifth-day:
  calling-birds: four
  french-hens: 3
  golden-rings: 5
  partridges:
    count: 1
    location: "a pear tree"
  turtle-doves: two
  martin: {name: Martin D'vloper, job: Developer, skill: Elite}
cars: GTO
```
Best regards and thank you for the answer.
