### ISSUE TITLE
Multi-line scalars that are the last in a sequence result in a parse error.

### ISSUE THREAD

**Issue by homer6** [biojppm/rapidyaml#152]
rapidyaml version: ffed564a090546c2568e4813457bd71dcc2adb19

![2021-08-29_16h13_39](https://user-images.githubusercontent.com/371329/131268397-9b56809e-63f6-4c4e-b015-40f2cd4371b5.png)

![2021-08-29_16h14_52](https://user-images.githubusercontent.com/371329/131268420-85f5fecf-d13f-4b88-b9ab-1b5a8a20b1c0.png)

```
128:13: (4029B):ERROR:
/home/user/rapidyaml/src/c4/yml/parse.cpp:760: ERROR parsing yml: parse error
line 128: '            periodSeconds: 10' (sz=29)
                       ^~~~~~~~~~~~~~~~~  (cols 13-30)

Aborted (core dumped)
```

**Comment by homer6** [comment]
Minimal failing input:

```
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    spec:      
      containers:
        - name: postgresql
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "dog" -d "dbname=dog" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
            periodSeconds: 10
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
```
