### ISSUE TITLE
Block style: parses incorrectly maps nested in seqs when the map values are missing

### ISSUE THREAD

**Issue by biojppm** [biojppm/rapidyaml#209]
```yaml
--- # incorrect
a:
  - :<spc>
  - :<spc>
--- # incorrect
a:
  - :
  - :
--- # ok
a:
  - ~: ~
  - ~: ~
```
