### ISSUE TITLE
[Bug] Keys with ":" cause the value on the next line to be treated as an unquoted scalar

### ISSUE THREAD

**Issue by Waikuteru** [biojppm/rapidyaml#377]
Hello,

I noticed a bug where if you use colons in the key name like this:
```
const game::perception::PerceiveData:
      PerceiveData: {default: nullptr}
```

in YAML, it leads to the following error using the rapidyaml lib:

![image](https://github.com/biojppm/rapidyaml/assets/89609865/5f0e4e24-3edb-4968-b4cf-a1563ee303a0)

Keys with : cause the value on the next line to be treated as an unquoted scalar, and might also cause it to split the key up into many key-pair mappings.

This syntax is able to be parsed (removing the other colons) but obviously don't work as a workaround because the key is different:

```
const gameperceptionPerceiveData:
      PerceiveData: {default: nullptr}
```

Would be cool if you can fix it!

**Comment by biojppm** [comment]
Cannot reproduce this. The following code succeeds:
```c++
TEST(simple_map, issue377)
{
    csubstr yaml = R"(
const game::perception::PerceiveData:
      PerceiveData: {default: nullptr}
)";
    test_check_emit_check(yaml, [](Tree const &t){
        ASSERT_TRUE(t.rootref().has_child("const game::perception::PerceiveData"));
        const ConstNodeRef cpd = t["const game::perception::PerceiveData"];
        ASSERT_TRUE(cpd.is_map());
        ASSERT_TRUE(cpd.has_child("PerceiveData"));
        ASSERT_EQ(cpd["PerceiveData"].num_children(), 1u);
        ASSERT_TRUE(cpd["PerceiveData"].has_child("default"));
        ASSERT_EQ(cpd["PerceiveData"]["default"].val(), "nullptr");
    });
}
```
The [YAML playground also succeeds](https://play.yaml.io/main/parser?input=Y29uc3QgZ2FtZTo6cGVyY2VwdGlvbjo6UGVyY2VpdmVEYXRhOgogICAgICBQZXJjZWl2ZURhdGE6IHtkZWZhdWx0OiBudWxscHRyfQo=):

![image](https://github.com/biojppm/rapidyaml/assets/325344/33ac06dc-c256-48d9-a20f-540767db0633)

Maybe you are using an older version of rapidyaml?

**Comment by biojppm** [comment]
@Waikuteru have you checked what is going on? are you sure the error you are seeing comes from the YAML you posted, and that the version is up-to-date?

**Comment by Waikuteru** [comment]
Sorry for the late response. It does seem that the tool I used is using an old version of rapidyaml and it's probably the reason why it's bugged.

**Comment by Mr-S-Mirzoev** [comment]
Hey there, I believe I'm able to reproduce the bug:

```yaml
c: "proxy"
a:p_p:
  c: "clean"
  m: !<SomeClass> [/some/path]
a:d_d:
  c: "proxy"
  m: !<SomeClass> [/some/path]
```

<img width="1680" alt="image" src="https://github.com/biojppm/rapidyaml/assets/61053551/ade22435-8e99-4f16-b3a0-4502b3a786d6">

```log
-:8:4: (48B): ERROR: ': ' is not a valid token in plain flow (unquoted) scalars
-:8:4:   c: "clean"  (size=12)
          ^~~~~~~~~  (cols 4-13)
```

Indeed, it is some issue with keys with colons since the same yaml with keys without colons is parsed successfully by RYML:

```yaml
c: "proxy"
p_p:
  c: "clean"
  m: !<SomeClass> [/some/path]
d_d:
  c: "proxy"
  m: !<SomeClass> [/some/path]
```

<img width="1680" alt="image" src="https://github.com/biojppm/rapidyaml/assets/61053551/c5804e35-1b2b-4c74-8ccd-c4e018f431a7">

I also noticed that if you quote the keys, RYML parses successfully too.

```yaml
c: "proxy"
"a:p_p":
  c: "clean"
  m: !<SomeClass> [/some/path]
"a:d_d":
  c: "proxy"
  m: !<SomeClass> [/some/path]
```

<img width="1680" alt="image" src="https://github.com/biojppm/rapidyaml/assets/61053551/611bc8e8-f1d6-4c4a-84ef-d46db8e1e5ea">

Also, if this helps, the library acts weird and fails in this example only on the second element with a colon-containing key:

```yaml
a:p_p:
  c: "clean"
  m: !<SomeClass> [/some/path]
c: "text"
a:d_d:
  c: "proxy"
  m: !<SomeClass> [/some/path]
```

<img width="1680" alt="image" src="https://github.com/biojppm/rapidyaml/assets/61053551/e97d8d4d-7d90-4dbf-a3a3-c628faed2f07">

In case you don't see comments on this closed issue, let me mention you: @biojppm
