### ISSUE TITLE
Parsing YAML with unquoted \0 characters

### ISSUE THREAD

**Issue by stohrendorf** [biojppm/rapidyaml#439]
This is the code which loads the YAML:
```cpp
      std::ifstream file{filename, std::ios::in | std::ios::binary};
      gsl_Assert(file.is_open());
      file.seekg(0, std::ios::end);
      const auto size = static_cast<std::streamsize>(file.tellg());
      file.seekg(0, std::ios::beg);

      m_buffer.resize(size);
      file.read(m_buffer.data(), size);
      m_tree = ryml::parse_in_arena(c4::to_csubstr(m_buffer));
```

This is the YAML is should parse, including a newline at the end:
```
meta:
  title: "Croft Arena"
  author: "JaayStation, SOTOS"
  downloadSoundtrack: false
  urls:
    - "https://drive.google.com/file/d/1fJ1Z3Ktr2VlPK1MD5OB4tY7uDnqyRMEQ/view?usp=sharing"
```

However, in version 0.7.0, rapidyaml throws an error that it's missing a colon after the key at line 7, column 2, which is an empty line, and beyond the size of the buffer. It works fine with 0.6.0, so I'm wondering if there's a breaking change regarding the new parser I don't fully grasp, or if it's an actual bug regarding handling of null terminators. When I remove the `std::ios::binary`, it complains about column 7, which indicates the latter, as the file has 7 lines with `\r\n` terminators, and the debugger showed me that the buffer contained only plain `\n`'s.
