### ISSUE TITLE
Parser regression in 0.7.0

### ISSUE THREAD

**Issue by marcalff** [biojppm/rapidyaml#455]
The following yaml parses fine with 0.6.0:

```
file_format: 0.0
tracer_provider:
  processors:
    - simple:
        exporter:
          console:
  sampler:
    trace_id_ratio_based:
      ratio:
```

With 0.7.0, I get a parse error on `sampler:`:

```
8:3: (102B): ERROR: parse error
8:3:   sampler:  (size=10)
       ^~~~~~~~  (cols 3-11)
```
