### ISSUE TITLE
Adding dynamic keys (from short-living local strings)

### ISSUE THREAD

**Issue by rlalik** [biojppm/rapidyaml#500]
Hi,

first time using the library, and I have an issue with making dynamic keys (the string is generated and has short life time).

I would like to have following structure:
```yaml
- DynamicKey1:
  - 0:
    key1: val1
    key2: val2
  -1:
    key1: val1
    key2: val2
- DynamicKey2:
... and so on...
```
I start with some initial `content`:
```c++
auto tree = ryml::parse_in_arena(content.c_str());
auto treeroot = tree.rootref();
if (!treeroot.is_map()) {  // content may be empty
    treeroot |= ryml::MAP;
}
```
and now I want to add the key:
```c++
{ // brackets to limit scope for dynkey variable
    auto dynkey = fmt::format("DynamicKey{}", 1);
    // what to do here to add the key == dynkey, of which value is an another map: - DynamicKey1:
    auto dynnode = /* ... */;

    auto key0 = dynnode["0"];
    key0 |= ryml::MAP;
    key0["key1"] << fmt::format("val{}", 1).c_str();
}

// emit valid yaml
std::ofstream infile { "file_path" };
infile << tree;
```
Can you help me with this? The `quickstart.cpp` doesn't cover this I think. Perhaps you can include this?
